### ISSUE TITLE
带有数值属性的互动视频

### ISSUE THREAD

**Issue by MiracleXYZ** [MiracleXYZ/bili-interactive-spoiler#1]
目前我还没有看到这一类，如果有的话请在下面留言哦~

**Comment by MiracleXYZ** [comment]
Found one: https://www.bilibili.com/video/av65760443

**Comment by MiracleXYZ** [comment]
在 `GET https://api.bilibili.com/x/stein/nodeinfo` 中有两个参数值得注意：
1. `buvid`: 请求的Session id
2. `delay`: 选择选项迟疑的时间长度（ms）

目前看来没有找到数值区分的显式方法，比较可靠的方法是使用一个Session来explore所有结果（经测试回退操作是可行的）……然后在最后生成图的同时，对每个结局，给出至少一种达成的方法。（也许可以猜出一些达成条件）

这种互动视频可以做的非常复杂，而我们看到的只不过是冰山上的一角，要想全部spoil出来还是得花时间啊……

**Comment by howmp** [comment]
这里还有一个 https://www.bilibili.com/video/av73267982/

由于本身会有循环，所以会导致爆栈

```txt
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    nodes = get_node(get_node_info()['data']['node_id'])
  File "main.py", line 74, in get_node
    choice.update(get_node(choice['node_id']))
  File "main.py", line 74, in get_node
    choice.update(get_node(choice['node_id']))
  File "main.py", line 74, in get_node
    choice.update(get_node(choice['node_id']))
  [Previous line repeated 995 more times]
  File "main.py", line 56, in get_node
    if node_id in node_infos.keys():
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by howmp** [comment]
改造了一下，解决了爆栈问题。但是看起来带变量的会根据变量的情况展示不同选项。

按照av73267982，最终应该会出现沉默的选项，游戏才能结束。但如果才能遍历到相应变量的分支呢？

```py
# coding: utf-8
from graphviz import Digraph
import requests
import time
from bs4 import BeautifulSoup
import json
from config import *


def get_graph_version(aid):
    videopage = requests.get(
        'https://api.bilibili.com/x/web-interface/view?aid={}'.format(
            aid)).json()
    cid = videopage['data']['pages'][0]['cid']

    headers = {
        'Accept':
        '*/*',
        'Referer':
        'https://www.bilibili.com/video/av{}'.format(aid),
        'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36',
        'Sec-Fetch-Mode':
        'cors',
    }

    params = (
        ('id', 'cid:{}'.format(cid)),
        ('aid', str(aid)),
    )

    player = requests.get(
        'https://api.bilibili.com/x/player.so', headers=headers, params=params)
    player.encoding = player.apparent_encoding
    soup = BeautifulSoup(player.text, 'lxml')
    interaction = json.loads(soup.select('interaction')[0].get_text())
    graph_version = interaction['graph_version']
    print('graph_version: {}'.format(graph_version))
    return graph_version


graph_version = get_graph_version(aid)
nodes = {}
edges = set()


def get_node_info(node_id=''):
    url = 'https://api.bilibili.com/x/stein/nodeinfo'
    params = {
        'aid': aid,
        'node_id': node_id,
        'graph_version': graph_version,
        'platform': 'pc',
        'portal': 0,
        'screen': 0,
    }
    data = requests.get(url, params=params).json()
    time.sleep(interval)
    return data


def traverse_nodes(node_id):

    if node_id not in nodes:
        print(node_id)
        info = get_node_info(node_id)['data']
        if 'edges' in info.keys():
            choices = info['edges']['choices']
        else:
            choices = []

        node = {'node_id': node_id, 'title': info['title'], 'choices': choices}
        node_params = {'name': str(node_id), 'label': info['title']}
        G.node(**node_params)
        nodes[node_id] = node
        for choice in node['choices']:
            traverse_nodes(choice['node_id'])
            edgename = '{}-{}'.format(node_id, choice['node_id'])
            if edgename not in edges:
                edge_params = {
                    'tail_name': str(node_id),
                    'head_name': str(choice['node_id']),
                    'label': choice.get('option', 'START')
                }
                edges.add(edgename)
                G.edge(**edge_params)


if __name__ == '__main__':
    G = Digraph(
        'av{}'.format(aid),
        node_attr={'fontname': fontname},
        edge_attr={'fontname': fontname},
        strict=True)

    traverse_nodes(get_node_info()['data']['node_id'])

    G.render(output, format=output_format)

    print('')
    print('Done.')
```
![graphviz](https://user-images.githubusercontent.com/10806806/67687062-ae0c4980-f9d2-11e9-8af9-32027560661b.png)

**Comment by howmp** [comment]
找到思路了，在登录的状态下，get_node_info返回的story_list是包含了一部分节点数据。基本就可以补全整个图了。
![graphviz (2)](https://user-images.githubusercontent.com/10806806/67691499-aac88c00-f9d9-11e9-916e-9b0f99663dbf.png)

**Comment by MiracleXYZ** [comment]
感谢，因为我创建这个 repo 的时候还不能设置剧情闭环，所以并没有遇到你说的这个问题，忙完这阵之后会考虑修补一下；

另外利用 `story_list` 这件事我也在考虑了，判定条件未知的情况下，这几乎是 explore 所有剧情的唯一方法。
